### ISSUE TITLE
Error running train.py s3dis: The deleter and context arguments are mutually exclusive.

### ISSUE THREAD

**Issue by anhthuan1999** [dvlab-research/Stratified-Transformer#23]
I have some errors when I run train.py based on your guideline on s3dis dataset. I also keep configuration files and install libraries like requirements.txt. Because I use Cuda 11.3, I install torch 1.10.0+cu113 and torch_geometric 1.10.0+cu113

[05/27 14:35:26 main-logger]: #Model parameters: 7069114
[05/27 14:35:28 main-logger]: augmentation all
[05/27 14:35:28 main-logger]: jitter_sigma: 0.005, jitter_clip: 0.02
Totally 204 samples in train set.
[05/27 14:35:28 main-logger]: train_data samples: '6120'
Totally 67 samples in val set.
[05/27 14:35:28 main-logger]: scheduler: MultiStep. scheduler_update: epoch. milestones: [60, 80], gamma: 0.1
[05/27 14:35:28 main-logger]: lr: [0.006, 0.0006000000000000001]
WARNING [05/27 14:35:30 main-logger]: batch_size shortened from 2 to 1, points from 160000 to 80000
WARNING [05/27 14:35:30 main-logger]: batch_size shortened from 2 to 1, points from 160000 to 80000
WARNING [05/27 14:35:30 main-logger]: batch_size shortened from 2 to 1, points from 143440 to 63440
WARNING [05/27 14:35:31 main-logger]: batch_size shortened from 2 to 1, points from 157885 to 77885
WARNING [05/27 14:35:31 main-logger]: batch_size shortened from 2 to 1, points from 159069 to 80000
WARNING [05/27 14:35:31 main-logger]: batch_size shortened from 2 to 1, points from 160000 to 80000
torch.Size([108012, 3])
0.0025000000000000005
WARNING [05/27 14:35:32 main-logger]: batch_size shortened from 2 to 1, points from 144512 to 80000
WARNING [05/27 14:35:32 main-logger]: batch_size shortened from 2 to 1, points from 140900 to 66523
WARNING [05/27 14:35:33 main-logger]: batch_size shortened from 2 to 1, points from 160000 to 80000
Traceback (most recent call last):
  File "train.py", line 543, in <module>
    main()
  File "train.py", line 84, in main
    main_worker(args.train_gpu, args.ngpus_per_node, args)
  File "train.py", line 306, in main_worker
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, criterion, optimizer, epoch, scaler, scheduler)
  File "train.py", line 363, in train
    neighbor_idx = tp.ball_query(radius, args.max_num_neighbors, coord, coord, mode="partial_dense", batch_x=batch, batch_y=batch)[0]
  File "/home/pknu/anaconda3/envs/testPt/lib/python3.7/site-packages/torch_points_kernels/torchpoints.py", line 210, in ball_query
    return ball_query_partial_dense(radius, nsample, x, y, batch_x, batch_y, sort=sort)
  File "/home/pknu/anaconda3/envs/testPt/lib/python3.7/site-packages/torch_points_kernels/torchpoints.py", line 167, in ball_query_partial_dense
    ind, dist = tpcpu.batch_ball_query(x, y, batch_x, batch_y, radius, nsample, mode=0, sorted=sort)
ValueError: The deleter and context arguments are mutually exclusive.

**Comment by X-Lai** [comment]
Have you modified the code? or the config?

It seems that the function causing the error is from torch_points3d. If you don't modify anything, the error may be caused by an unsuccessful installment of torch_points3d.

**Comment by anhthuan1999** [comment]
Thank you for your kind response. I have installed same version torch_points3d (1.3.0). However, I use only 1 GPU because of limited hardware, so I just modify config: multiprocessing_distributed (set to False) and train_gpu (set to [0])

**Comment by X-Lai** [comment]
Then you may adjust the `batch_size` accordingly. Perhaps you may also check whether the model has already been moved to cuda device.

**Comment by Shadow-Assassin** [comment]
Hi, I got the same problem, have you found out the reason? @anhthuan1999
