### ISSUE TITLE
RuntimeError: CUDA error: too many resources requested for launch

### ISSUE THREAD

**Issue by Lature-Yang** [dvlab-research/Stratified-Transformer#24]
Thanks for your excellent work!
When I train the s3dis_stratified_transformer, I meet the following the error? The version of torch, cuda is 1.9.0 and 10.2 respectively.  Have you ever met this ?

/root/miniconda3/envs/point/lib/python3.7/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448224956/work/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
/root/miniconda3/envs/point/lib/python3.7/site-packages/torch/nn/functional.py:652: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448224956/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool1d(input, kernel_size, stride, padding, dilation, ceil_mode)
/root/miniconda3/envs/point/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
  len(cache))
/root/miniconda3/envs/point/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 17 leaked semaphores to clean up at shutdown
  len(cache))
/root/miniconda3/envs/point/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "exp/s3dis/stratified_transformer/train.py", line 585, in <module>
    main()
  File "exp/s3dis/stratified_transformer/train.py", line 80, in main
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args.ngpus_per_node, args))
  File "/root/miniconda3/envs/point/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/envs/point/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/root/miniconda3/envs/point/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/point/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/root/Project/Stratify-TR/exp/s3dis/stratified_transformer/train.py", line 345, in main_worker
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, criterion, optimizer, epoch, scaler, scheduler)
  File "/root/Project/Stratify-TR/exp/s3dis/stratified_transformer/train.py", line 418, in train
    output = model(feat, coord, offset, batch, neighbor_idx)
  File "/root/miniconda3/envs/point/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/point/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/point/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/Project/Stratify-TR/model/stratified_transformer.py", line 556, in forward
    feats, xyz, offset, feats_down, xyz_down, offset_down = layer(feats, xyz, offset)
  File "/root/miniconda3/envs/point/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/Project/Stratify-TR/model/stratified_transformer.py", line 393, in forward
    feats = blk(feats, xyz, index_0, index_1, index_0_offsets, n_max)
  File "/root/miniconda3/envs/point/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/Project/Stratify-TR/model/stratified_transformer.py", line 295, in forward
    feats = self.attn(feats, xyz, index_0, index_1, index_0_offsets, n_max) # index_0 MUST be in ascending order
  File "/root/miniconda3/envs/point/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/Project/Stratify-TR/model/stratified_transformer.py", line 235, in forward
    attn_flat = attn_flat + relative_position_bias #[M, num_heads]
RuntimeError: CUDA error: too many resources requested for launch
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by Lature-Yang** [comment]
I have solved this. The TOTAL_THREADS is set from 1024 to 256 in lib/src/cuda_utils.sh, and re-install it~
