### ISSUE TITLE
RuntimeError: Unkown device

### ISSUE THREAD

**Issue by plusgrey** [dvlab-research/Stratified-Transformer#30]
Hi, thanks for your great project firstly. However, when I was running your project, I encountered such an error below. I set gpus and multiprocessing_distributed in config according to my computer correctly, but still got this error. Could you please help me with it? Many thanks ahead

Traceback (most recent call last):
  File "train.py", line 542, in <module>
    main()
  File "train.py", line 84, in main
    main_worker(args.train_gpu, args.ngpus_per_node, args)
  File "train.py", line 306, in main_worker
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, criterion, optimizer, epoch, scaler, scheduler)
  File "train.py", line 363, in train
    neighbor_idx = tp.ball_query(radius, args.max_num_neighbors, coord, coord, mode="partial_dense", batch_x=batch, batch_y=batch)[0]
  File "/home/user/anaconda3/envs/torch3d/lib/python3.8/site-packages/torch_points_kernels/torchpoints.py", line 210, in ball_query
    return ball_query_partial_dense(radius, nsample, x, y, batch_x, batch_y, sort=sort)
  File "/home/user/anaconda3/envs/torch3d/lib/python3.8/site-packages/torch_points_kernels/torchpoints.py", line 167, in ball_query_partial_dense
    ind, dist = tpcpu.batch_ball_query(x, y, batch_x, batch_y, radius, nsample, mode=0, sorted=sort)
RuntimeError: Unknown device: -27. If you have recently updated the caffe2.proto file to add a new device type, did you forget to update the DeviceTypeName() function to reflect such recent changes?

**Comment by plusgrey** [comment]
Fixed! Use following setup:
gcc 11.02
pytorch 1.10.1
cuda 11.6
After recreate the enviorment, the problem was gone!
