### ISSUE TITLE
在Evaluation阶段显存占用会突然提高，然后OOM

### ISSUE THREAD

**Issue by clawCa** [dvlab-research/Stratified-Transformer#47]
**[07/22 17:59:29 main-logger]: >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>**
Traceback (most recent call last):
  File "/media/zhu/软件/python projet/Stratified-Transformer/train_zhu.py", line 569, in <module>
    main()
  File "/media/zhu/软件/python projet/Stratified-Transformer/train_zhu.py", line 86, in main
    main_worker(args.train_gpu, args.ngpus_per_node, args)
  File "/media/zhu/软件/python projet/Stratified-Transformer/train_zhu.py", line 342, in main_worker
    loss_val, mIoU_val, mAcc_val, allAcc_val = validate(val_loader, model, criterion)
  File "/media/zhu/软件/python projet/Stratified-Transformer/train_zhu.py", line 517, in validate
    output = model(feat, coord, offset, batch, neighbor_idx)
  File "/home/zhu/anaconda3/envs/pct/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhu/anaconda3/envs/pct/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zhu/anaconda3/envs/pct/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/zhu/软件/python projet/Stratified-Transformer/model/stratified_transformer.py", line 438, in forward
    feats = layer(feats, xyz, batch, neighbor_idx)
  File "/home/zhu/anaconda3/envs/pct/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/zhu/软件/python projet/Stratified-Transformer/model/stratified_transformer.py", line 357, in forward
    feats = self.kpconv(xyz, xyz, neighbor_idx, feats)
  File "/home/zhu/anaconda3/envs/pct/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhu/anaconda3/envs/pct/lib/python3.7/site-packages/torch_points3d/modules/KPConv/kernels.py", line 92, in forward
    self.aggregation_mode,
  File "/home/zhu/anaconda3/envs/pct/lib/python3.7/site-packages/torch_points3d/modules/KPConv/convolution_ops.py", line 63, in KPConv_ops
    sq_distances = torch.sum(differences ** 2, dim=3)
**RuntimeError: CUDA out of memory. Tried to allocate 11.81 GiB (GPU 0; 23.70 GiB total capacity; 13.35 GiB already allocated; 7.47 GiB free; 14.86 GiB reserved in total by PyTorch)**

进程已结束,退出代码1

**Q1: Start Evaluation会OOM**
我是在的其他是数据集跑的，把参数改小后不会OOM但是效果很差
![image](https://user-images.githubusercontent.com/71144235/180416873-f9f42839-ef27-4fdf-b7bb-0c617e497766.png)

  grid_size: 0.01    #原_0.04  0.01
  max_batch_points: 500000  #y_140000
  max_num_neighbors: 16  # For KPConv  34  2
  ratio: 0.25
  k: 16       #10
-------更详细的config在最后

能给给一些建议吗？

**Q2:由于pheno4d的数据集是没有颜色的，但是改写dataloader中feat涉及很多其他地方**
coord, feat, label = data[:, 0:3], np.zeros_like(data[:,0:3]), data[:, 3]
我就简单的赋值为0的，有方法可以取消feat吗？
config中DATA: fea_dim: 3 好像修改没用

**Q3:在另一个issue有2个论文相关的疑问，如果能解答一下就太好了**
希望能获得您的邮箱，ff296753781@gmail.com  十分感谢！

下面是我的config文件
[pheno4d.zip](https://github.com/dvlab-research/Stratified-Transformer/files/9166824/pheno4d.zip)

这是我跑100epoch 的结果--第4列是训练用的label，第6列是pred的label
[pred_data1.zip](https://github.com/dvlab-research/Stratified-Transformer/files/9166940/pred_data1.zip)
[pred_data2.zip](https://github.com/dvlab-research/Stratified-Transformer/files/9166957/pred_data2.zip)

**Comment by clawCa** [comment]
This issue is over due to a mismatch between voxel size and point cloud data;
New Question Q1:
How to implement the learnable position encoding table in the paper? I hope someone can answer
